name: Release Shared Workflow

on:
  # schedule:
  #   - cron: '0 * * * *'  # Runs every 24 hours
  push:
    tags:
      - 'v*.*.*'
      - 'daily'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [1,2,3,4,5,6,7,8,9,10,
                11,12,13,14,15,16,17,18,19,20,
                21,22,23,24,25,26,27,28,29,30,
                31,32,33,34,35,36]  # Indices for 37 parallel jobs
    continue-on-error: true  # Allow individual build jobs to fail
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Calculate Start Date
        id: calc_date
        run: |
          base_date=$(date -u +"%Y%m%d")
          index=${{ matrix.index }}
          default_num_days=10
          total_days=365
          start_offset=$(( index * default_num_days ))
          start_date=$(date -u -d "$base_date -$start_offset days" +"%Y%m%d")
          remaining_days=$(( total_days - index * default_num_days ))
          if [ $remaining_days -ge $default_num_days ]; then
            num_days=$default_num_days
          elif [ $remaining_days -gt 0 ]; then
            num_days=$remaining_days
          else
            echo "No days left to process."
            exit 0
          fi
          echo "start_date=${start_date}" >> $GITHUB_ENV
          echo "num_days=${num_days}" >> $GITHUB_ENV

      - name: Run Historical Data Download
        run: |
          chmod +x ./ncar.sh
          ./ncar.sh $start_date $num_days || true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.grib2
          prerelease: false
          tag_name: daily
